### ISSUE TITLE
databags

### ISSUE THREAD

**Issue by ncostis** [evertrue/shinken-cookbook#5]
I have a hard time to figure out the databags in shinken.
Can you please give me real examples of what i need?

Thank you

**Comment by jeffbyrnes** [comment]
Apologies that it is confusing! We did our best to make the README as explicit as possible. I’ll attempt again:

You need two data bag items.

One of them is an unencrypted data bag item inside the `users` data bag, corresponding to a user that has access to Shinken. As stated, this is based on the [`users` cookbook](https://github.com/sethvargo-cookbooks/users), so you will want to check out how that cookbook makes use of a data bag to define the users on your system.

So we could create a `testuser` data bag item inside the `users` data bag, and configure it like so:

```json
{
  "id": "testuser",
  "shinken": {
    "email": "testuser@domain.com",
    "phone": "6175551212",
    "is_admin": "1"
  }
}
```

As for the credentials, you have some flexibility here. The data bag item that is read from to get the credentials is defined using a pair of attributes. They are:

* `default['shinken']['agent_key_data_bag'] = 'secrets'`
* `default['shinken']['agent_key_data_bag_item'] = 'monitoring'`

So you can create a data bag called `secrets`, and within it have a data bag item called `monitoring`, with a structure like so:

```json
{
  "id": "monitoring",
  "shinken": {
    "testuser": "PASSWORD"
  }
}
```

The cookbook will read whatever data bag & item you’ve defined in those attributes, and then load in the `shinken` key from that data bag item. The `testuser` bit corresponds to the user you’ve defined in the `users` data bag.

So, using the defaults, you’d have:

* one or more `users` data bag item, for your user(s)
* a `monitoring` item in your `secrets` data bag, with a key called `shinken` in it, and one or more hash items within that key, each one corresponding to a user you’ve defined in your `users` data bag.

I realize that’s a bit convoluted, but I hope that lays it out some more.

**Comment by ncostis** [comment]
Yes that was very clear now and thank you indeed :-)

The cookbook moved ahead but now i got 

NoMethodError
-------------
undefined method `each' for nil:NilClass
Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/shinken/recipes/_services.rb:36:in `from_file'
  /var/chef/cache/cookbooks/shinken/recipes/definitions.rb:20:in `from_file'
  /var/chef/cache/cookbooks/shinken/recipes/default.rb:53:in `from_file'
Relevant File Content:
----------------------
/var/chef/cache/cookbooks/shinken/recipes/_services.rb:
 29:      file "#{node['shinken']['conf_dir']}/services/#{svc}.cfg" do
 30:        action :delete
 31:        notifies :restart, 'service[shinken-arbiter]'
 32:      end
 33:    end
 34:  end
 35:  
 36>> node['shinken']['services'].each do |svc_name, svc_conf|
 37:    if svc_conf['hostgroup_name'] &&
 38:       !node['shinken']['hostgroups'][svc_conf['hostgroup_name']]
 39:      fail "Service #{svc_name} refers to hostgroup " \
 40:        "#{svc_conf['hostgroup_name']} but that hostgroup does not seem to " \
 41:        'exist.'
 42:    end
 43:  
 44:    template "#{node['shinken']['conf_dir']}/services/#{svc_name}.cfg" do
 45:      source 'generic-definition.cfg.erb'

If this tells you something 

thank you

**Comment by jeffbyrnes** [comment]
@ncostis it would seem you have not defined any `node['shinken']['services']` to monitor, and without anything defined, there is no `each` method available.

There is no default value for `node['shinken']['services']`.

You can read up on how these attributes should be defined in the [Attributes section of the README](https://github.com/evertrue/shinken-cookbook#attributes).

We’ve gotten off-topic from your original question; please open a new issue for any additional questions.
